graph TD
	r[static memes and an additional origin which explains humanity's long period of stagnation.<br>Memes:]

  r---p1[generated in the mind]
  r---p2[mutate in the mind]
  r---p3[influenced by our biological brain]
  r---p4[and young children]


  p1 --- p11[we can generate them by using creativity<br>to replicate meaning. This is the same mechanism<br> needed to create them.]
  p11 --- p1111[so they can be generated without interpreting another's<br>behaviour provided theres some comparably good<br>explanation for why they'd be generated]
  p1111---p111["the exact memes are generated depend on<br>the person's mental state; their environment,<br> e.g. natural selection pressures, or their tribe and<br>relevant memes; and the other ideas and memes<br>they have already."]
  p111---p11a["a consistent set up works for consistent replication<br>(e.g. being treated badly during school w/ reward based<br>on conformity)."]
  p11a---p11b["so if we had a consistent set up and a reason for creative<br>effort to be spent, it only needs to be consistent<br>for every culture over 180k years"]


  p2 --- p21[creativity was used in static societies<br>to do replication well and thus impress<br>people and the tribe.<br>]
  p21---p22["`Status in such a society is reduced by<br>transgressing people’s expectations of<br>proper behaviour, and is improved by<br>meeting them.` &mdash; DD, BoI, Ch16"]
    	
  p22---p23["There was a selection pressure in favour of<br>those ppl better capable of 
  satisfying<br>other ppl and the rest of the tribe's expectations."]
  
  p23---p24["after replicating a meme, you can only<br>improve it by repeating the replication,<br>or by mutating without another human...<br>intra-mind replication."]
  
  p23---p23c["Parents want children who also satisfy tribal<br>expectations and their own (even if they know<br>their own are arbitrary)<br>(p23c)"]
  
  p24["relevant selection pressures are:<br>1. Existing memes to suppress competitors<br>(including newer versions of itself)<br>2. continue satisfying behavioural requirements<br>well, even if it means the person knowlingly<br>pretends to believe a lie, thats okay as long as the<br>behaviour, and thus replication, persist."]
  
  p24---p25a["applys to memes; existential risk"]  
  p24---p25e["applys to genes"]
  
  p25a---p26a["it could be replaced by a better version,<br>or be kicked out entirely"]
  
  p26a---p27a["occasionally, someone will seem to loose faith<br>or change their mind on something out of nowhere.<br>The trigger can be otherwise<br>small and insignificant. Some of the time,<br>Is this why?"]
  
  p25a---p26b["Futher selection pressure in favour of<br>static memes. i.e. to direct creativity away<br>from rationality. Any other subject is better. other<br>memes are a less risky target than itself, and <br>and applying creativity to them might reduce competition<br> as a bonus."]
  p26b---p27b
  p26a-.-p27b
  p27b["Memes experience selection pressure which directs<br>creativity to **mutate other memes** _and_ itself,<br>provided the resulting behavioural expressions<br>of the mutation matchs expectations."]
  p27b---p29b["memes are most powerful when they can be expressed, and<br>anti-rational people are more suceptabile the more<br>creative they are _at meeting expectations_.<br>Botin increase with age (at least for a while)"]
  p29b---p29c["**more creativity means memes are more significant.**<br>survival is less luck based because we're smarter,<br>which *increases* importance of a good, safe early<br>childhood (after which the brain does more work)<br>(p29c)"]
  p29c---p29d["How do parents and tribe come to be satisfied?<br>(p29d)"]
    
  p23c -.- p29d
	
	
  %% p3---p3i["Human memes can have more powerful effects<br>than ape memes."]
  
  p3---p3a["We evolved from advanced apes with<br>some capacity for memetic information.<br>(BoI)"]
  p3a --- p3b["The biological brain alters which<br>memes can and can't be replicated<br>through us &mdash; depending on creativity<br>and storeage capacity."]
  p3b --- p3c["`our inborn capacity for reasoning itself<br>is software` and we could have other<br>inborn ideas too. curi.us/1531/#11672"]
  p3c --- p3d["when people are young, these inborn ideas are<br>our starting point, and we have to interpret<br>everything through and with them till we learn better."]
  p3d---p3e["these ideas have made the jump to universality.<br>they have reach. losing them is too expensive,<br>but they're hard to change. so selection pressure<br>ends up being applied elsewhere:<br>other companion inborn ideas."]
  p3ea
  p3e---p3eb["inborn capacity for reasoning is difficult to remove,<br>so can be a consistent factor for 180k years."]
  
  p3e---p3ea["they were crucial for competetiveness so were<br>selected for."]
  p3ea---p3ea1["they were hard to vary, and thus resilient to<br>genetic mutation."]
  p3ea1---p3ea2["."]
  
  p4---p4a["children are very creative, but also not bound<br>by taboo and the existing meme-pool."]
  p4a -.->|mistreated by| p23c
  
  p4a---p4b["are mistreated to some degree from birth<br>(or close enough to not matter)"]
  p4b---p4c["degree doesn't matter that much. no child developes<br>faster because they're *not* being eaten by a lion"]
  p4c---p4d["a good way to stay alive is meet expectations"]
  
  p23c -.-> p4d
  
  p4d---p5d["but a child needs to be doing this VERY early,<br>even before they've picked up many or any implicit<br>ideas"]
  p5d---p5d1["Selection pressure to develop inborn ideas that prepare<br>for children for the next (say) 5 yrs.<br>e.g. One safe-ish way to avoid being mistreated even<br>more is to treat every bad experience as though<br>you're the problem."]
  p5d---p5d2["implicit ideas are gathered slowly over first few<br>years of life and used to build up knowledge of the<br>world from there, especially via memes.<br>more memes become available very rapidly."]
  p5d1 & p5d2 --- p5e["selection pressure is to maintain anti-rational-<br>compatible early inborn ideas to maximise chance<br>of living to the point memes take over."]
