graph TD
r["test :: graph"]
subgraph sg-r ["#nbsp;"]
r --- r-0["has :: nodes"]

r --- r-1["indent :: whitespace"]

r --- r-2["is_s_expression == False"]
subgraph sg-r-2 ["#nbsp;"]
r-2 --- r-2-0["True"]

end
end
