graph TD
    table --- the3
    from --- table

    onto --- floor
    floor --- dirty
    floor --- the2

    fell --- from
    fell --- onto
    fell --- unfortunately
    fell --- cake
    
    cake --- delicious
    cake --- the1
    cake --- with 
    with --- berries
