graph TD

    or[overreaching]

    or --- a1[self-harm]

    or --- b1[benefits]

    or --- c1[how to see]




b1---helpsee[Helps you see thing's you're bad at you thought you were good at]
helpsee---hon[only if honest]
helpsee -.->|If dishonest| a1
