I'm sure there's more to write, but I don't know much about kids' development, or good philosophical discussion.
graph TD

Do you mean all discussion or particularly aural? (including things like phone calls, web conferences, too, but not async emails)
  * Does direct discussion mutually imply synchronicity?
  
Are there good things that are easier to do in direct discussion or happen more often?

Some possibilities that come to mind: (with some counterpoints and counter-counterpoints)
  * children learn some of their early morality from social interactions (doing harm, being harmed, etc)
    * but they can learn faster from other things, e.g. TCS
    * is there a replacement for kids? They might not know how to read or can't read well, etc.
    * also learning much faster than adults, so maybe good direct interaction is hard to surpass (for kids only) because demand > supply

  * in person reactions might make some (types of?) people consider their own behaviour in retrospect
    * compassion more likely if a "real person" is identified, tho only relevant if they're harmed
      * there are better ways to learn - needing to harm someone along the way is not good
    * introspection is always possible anyway, no need to involve doing it via direct comms
    * limited subject matter potential, esp if those types of ppl have a bias in who they directly communicate with

  * Aural communication sometimes has higher bandwidth than written comms or reading books
    * adaptive protocol, can easily increase bandwidth till more errors occur and back down (like network protocols)
    * reactive, too; books don't change their content based on the reader
      * less need to search for things
        * potentially curated experience
        * lower "admin/paperwork"-type overhead
      * with the *right pair* of ppl you might get high quality direct communication, but would be an outlier; appropriate specialisation required of both parties
        * population increase -> specialisation increase; fewer people to overlap with, *but* increased comparative value of ideas with *reach*
          * are philosophy discussions an exception? We would need a reason to think they have some advantage over e.g. FI
            * to be better the communication must be very theory-laden with enough good foundations to build on. just being interested in philosophy isn't enough. Presumably there's *some minimum threshold of the right ideas* necessary for this (if it does)

I'm sure there's more to write, but I don't know much about kids' development, or good philosophical discussion.
